AbcSize:
  Enabled: false
AlignParameters:
  Enabled: false
AndOr:
  Enabled: false
CaseEquality:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
DoubleNegation:
  Enabled: false
EachWithObject:
  Enabled: false
EndAlignment:
  AlignWith: variable
GuardClause:
  Enabled: false
IndentHash:
  Enabled: false
LineLength:
  Max: 100
MethodLength:
  Enabled: false
NonNilCheck:
  Enabled: false
ParameterLists:
  Max: 6
RegexpLiteral:
  Enabled: false
RescueException:
  Enabled: false
SignalException:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
TrailingComma:
  Enabled: false
TrivialAccessors:
  Enabled: false
